#!/usr/bin/env php

<?php

require_once __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;
use PHPKonf\Commands\PrintCommand;

$app = new Application('PHPKonf İzmir Demo App', 'v1.0.0');
$app -> add(new PrintCommand());
$app -> run();
